version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: SIS_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    networks:
      - SIS-network

  db:
    image: mysql:8.0
    container_name: SIS_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_management
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql
    networks:
      - SIS-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: SIS_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - SIS-network

networks:
  SIS-network:
    driver: bridge

volumes:
  db_data:
